PremiumBasket/Models/ErrorViewModel.cs
namespace ETradeCore8141.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PremiumBasket/Areas/Account/Controllers/UsersController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace MvcWebUI.Areas.Account.Controllers
{
    [Area("Account")] 
    public class UsersController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ICountryService _countryService;
        private readonly ICityService _cityService;

        public UsersController(IAccountService accountService, ICountryService countryService, ICityService cityService)
        {
            _accountService = accountService;
            _countryService = countryService;
            _cityService = cityService;
        }

        public IActionResult Register()
        {
            ViewBag.Countries = new SelectList(_countryService.GetList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(AccountRegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _accountService.Register(model);
                if (result.IsSuccessful)
                    return RedirectToAction("Login");
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.Countries = new SelectList(_countryService.GetList(), "Id", "Name");
            ViewBag.Cities = new SelectList(_cityService.GetCities(model.UserDetail.CountryId ?? 0), "Id", "Name");
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(AccountLoginModel model)
        {
            if (ModelState.IsValid)
            {
                UserModel userResult = new UserModel();
                var result = _accountService.Login(model, userResult);
                if (result.IsSuccessful)
                {
                    List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, userResult.UserName),
                        new Claim(ClaimTypes.Role, userResult.RoleName),
                        new Claim(ClaimTypes.Sid, userResult.Id.ToString())
                    };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                    return RedirectToAction("Index", "Home", new { area = "" });
                }
                ModelState.AddModelError("", result.Message);
            }
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home", new { area = "" });
        }

        public IActionResult AccessDenied()
        {
            return View("_Error", "You don't have access to this operation!");
        }
    }
}

PremiumBasket/Controllers/CartController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace MvcWebUI.Controllers
{
    public class CartController : Controller
    {
        private const string SESSIONKEY = "cart";

        private readonly IProductService _productService;

        public CartController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult GetCart()
        {
            List<CartItemModel> cart = GetCartFromSession();

            List<CartItemGroupByModel> cartGroupBy = (from c in cart
                                                      group c by new { c.ProductId, c.UserId, c.ProductName } into cGroupBy
                                                      select new CartItemGroupByModel()
                                                      {
                                                          ProductId = cGroupBy.Key.ProductId,
                                                          UserId = cGroupBy.Key.UserId,
                                                          ProductName = cGroupBy.Key.ProductName,
                                                          TotalUnitPrice = cGroupBy.Sum(cgb => cgb.UnitPrice).ToString("C2"),
                                                          TotalCount = cGroupBy.Count() + " pieces",
                                                          TotalUnitPriceValue = cGroupBy.Sum(cgb => cgb.UnitPrice),
                                                          TotalCountValue = cGroupBy.Count()
                                                      }).ToList();

            return View("CartGroupBy", cartGroupBy);
        }

        public IActionResult AddToCart(int productId)
        {
            List<CartItemModel> cart = GetCartFromSession();
            int userId = Convert.ToInt32(User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value);
            ProductModel product = _productService.Query().SingleOrDefault(p => p.Id == productId);
            if (product.StockAmount == 0)
            {
                TempData["Message"] = "Product cannot be added to cart because there is no product in stock!";
                return RedirectToAction("Index", "Products");
            }
            CartItemModel cartItem = new CartItemModel()
            {
                ProductId = productId,
                ProductName = product.Name,
                UnitPrice = product.UnitPrice ?? 0,
                UserId = userId
            };
            cart.Add(cartItem);
            string cartJson = JsonConvert.SerializeObject(cart);
            HttpContext.Session.SetString(SESSIONKEY, cartJson);
            TempData["Message"] = $"{product.Name} added to cart.";
            return RedirectToAction("Index", "Products");
        }

        private List<CartItemModel> GetCartFromSession()
        {
            List<CartItemModel> cart = new List<CartItemModel>();
            string cartJson = HttpContext.Session.GetString(SESSIONKEY);
            if (!string.IsNullOrWhiteSpace(cartJson))
            {
                cart = JsonConvert.DeserializeObject<List<CartItemModel>>(cartJson);
                
                int userId = Convert.ToInt32(User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value);
                cart = cart.Where(c => c.UserId == userId).ToList();
            }
            return cart;
        }

        public IActionResult ClearCart()
        {
            List<CartItemModel> cart = new List<CartItemModel>();
            string cartJson = JsonConvert.SerializeObject(cart);
            HttpContext.Session.SetString(SESSIONKEY, cartJson);

            TempData["Message"] = "Cart cleared.";
            return RedirectToAction(nameof(GetCart));
        }

        public IActionResult DeleteFromCart(int productId, int userId)
        {
            List<CartItemModel> cart = GetCartFromSession();
            CartItemModel cartItem = cart.FirstOrDefault(c => c.ProductId == productId && c.UserId == userId);
            if (cartItem is not null)
                cart.Remove(cartItem);

            string cartJson = JsonConvert.SerializeObject(cart);
            HttpContext.Session.SetString(SESSIONKEY, cartJson);

            TempData["Message"] = "Item removed from cart.";
            return RedirectToAction(nameof(GetCart));
        }
    }
}

PremiumBasket/Controllers/CategoriesController.cs
#nullable disable
using AppCore.Results.Bases;
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MvcWebUI.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            List<CategoryModel> categoryList = _categoryService.Query().ToList();
            return View(categoryList);
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            CategoryModel category = _categoryService.Query().SingleOrDefault(c => c.Id == id);
            if (category == null)
            {
                return View("_Error", "Category not found!");
            }
            return View(category);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            CategoryModel model = new CategoryModel()
            {
                Id = 0,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(CategoryModel category)
        {
            if (ModelState.IsValid)
            {
                Result result = _categoryService.Add(category);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(category);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            CategoryModel category = _categoryService.Query().SingleOrDefault(c => c.Id == id); 
            if (category == null)
            {
                return View("_Error", "Category not found!");
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(CategoryModel category)
        {
            if (ModelState.IsValid)
            {
                Result result = _categoryService.Update(category);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;

                    return RedirectToAction(nameof(Details), new { id = category.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(category);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            CategoryModel category = _categoryService.Query().SingleOrDefault(c => c.Id == id); 
            if (category == null)
            {
                return View("_Error", "Category not found!");
            }
            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmed(int id)
        {
            Result result = _categoryService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }

        
	}
}

PremiumBasket/Controllers/StoresController.cs
#nullable disable
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MvcWebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StoresController : Controller
    {
        private readonly IStoreService _storeService;

        public StoresController(IStoreService storeService)
        {
            _storeService = storeService;
        }

        public IActionResult Index()
        {
            List<StoreModel> storeList = _storeService.Query().ToList();
            return View(storeList);
        }

        public IActionResult Details(int id)
        {
            StoreModel store = _storeService.Query().SingleOrDefault(s => s.Id == id);
            if (store == null)
            {
                return View("_Error", "Store not found!");
            }
            return View(store);
        }

        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StoreModel store)
        {
            if (ModelState.IsValid)
            {
                var result = _storeService.Add(store);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            return View(store);
        }

        public IActionResult Edit(int id)
        {
            StoreModel store = _storeService.Query().SingleOrDefault(s => s.Id == id);
            if (store == null)
            {
                return View("_Error", "Store not found!");
            }
            return View(store);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StoreModel store)
        {
            if (ModelState.IsValid)
            {
                var result = _storeService.Update(store);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            return View(store);
        }

        public IActionResult Delete(int id)
        {
            StoreModel store = _storeService.Query().SingleOrDefault(s => s.Id == id);
            if (store == null)
            {
                return View("_Error", "Store not found!");
            }
            return View(store);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _storeService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
	}
}

PremiumBasket/Views/Shared/_Error.cshtml
@model string

@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>

@if (string.IsNullOrWhiteSpace(Model))
{
    <h2 class="text-danger">An error occurred while processing your request.</h2>
}
else
{
    <h2 class="text-danger">@Model</h2>
}

PremiumBasket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  Preimum Basket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ETradeCore8141.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">*@
        <nav class="navbar navbar-expand-lg navbar-light nav-bg">
            <a class="navbar-brand text-light" href="/">Premium Basket</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                    </li>

                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Stores" asp-action="Index">Stores</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Report" asp-controller="Home" asp-action="Index">Report</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="Db" asp-controller="Home" asp-action="Index">Seed Database</a>
                        </li>
                    }
                </ul>

                <div class="navbar-text">
                    <ul class="navbar-nav me-auto">

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Account" asp-controller="Users" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Account" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            if (User.IsInRole("User"))
                            {
                                <li class="nav-item">

                                    <a class="nav-link text-info" asp-area="" asp-controller="Cart" asp-action="GetCart">
                                        <i class="fa-solid fa-basket-shopping" style="color: #0dcaf0;"></i>
                                        Cart</a>
                                </li>
                            }

                            <li class="nav-item">
                                <span class="badge bg-info text-black" style="margin-top: 11px;">@User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Account" asp-controller="Users" asp-action="Logout">Logout</a>
                            </li>
                        }

                    </ul>

                </div>
        </nav>
    </header>

    @* <div class="container">
    <main role="main" class="pb-3">
    @RenderBody()
    </main>
    </div>*@
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    @*  <footer class="border-top footer text-muted">
    <div class="container">
    &copy; @DateTime.Now.Year - ETrade
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>